[package]
name = "tauri-windows-installer"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1.0.86"
toml = "0.8.19"

[target.'cfg(windows)'.dependencies]
webview2-com = "0.32.0"
windows = "0.58.0"

[build-dependencies]
reqwest = { version = "0.12.5", features = ["blocking"] }
tokio = "1.39.2"
toml = "0.8.19"
