[package]
name = "tauri-windows-installer"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
toml = "0.8.19"

[target.'cfg(windows)'.dependencies]
winreg = "0.52.0"

[build-dependencies]
reqwest = { version = "0.12.5", features = ["blocking"] }
tokio = "1.39.2"
toml = "0.8.19"
